# --*--utf-8--*--
import logging
import time

from prometheus_client import Gauge, start_wsgi_server, Counter, REGISTRY, PROCESS_COLLECTOR, PLATFORM_COLLECTOR
from win32com.client import GetObject

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

REGISTRY.unregister(PROCESS_COLLECTOR)
REGISTRY.unregister(PLATFORM_COLLECTOR)
REGISTRY.unregister(REGISTRY._names_to_collectors['python_gc_objects_collected_total'])

# VmmsVirtualMachineStats_HyperVVirtualMachineHealthSummary
# This counter represents the number of virtual machines with critical health.
virtual_machine_health_summary_health_critical = Gauge(
    subsystem='virtual_machine_health_summary',
    name='health_critical',
    documentation='This counter represents the number of virtual machines with critical health.',
)
# This counter represents the number of virtual machines with ok health.
virtual_machine_health_summary_health_ok = Gauge(
    subsystem='virtual_machine_health_summary',
    name='health_ok',
    documentation='This counter represents the number of virtual machines with ok health.',
)

# VidPerfProvider_HyperVVMVidPartition
# The number of physical pages allocated.
vm_vid_partition_physical_pages_allocated = Gauge(
    subsystem='vm_vid_partition',
    name='physical_pages_allocated',
    documentation='The number of physical pages allocated.',
    labelnames=['vm'],
)
# The preferred NUMA node index associated with this partition.
vm_vid_partition_preferred_numa_node_index = Gauge(
    subsystem='vm_vid_partition',
    name='preferred_numa_node_index',
    documentation='The preferred NUMA node index associated with this partition.',
    labelnames=['vm'],
)
# The number of physical pages not allocated from the preferred NUMA node.
vm_vid_partition_remote_physical_pages = Gauge(
    subsystem='vm_vid_partition',
    name='remote_physical_pages',
    documentation='The number of physical pages not allocated from the preferred NUMA node.',
    labelnames=['vm'],
)

# HvStats_HyperVHypervisorPartition
# The number of address spaces in the virtual TLB of the partition.
hypervisor_partition_address_spaces = Gauge(
    subsystem='hypervisor_partition',
    name='address_spaces',
    documentation='The number of address spaces in the virtual TLB of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of devices attached to the partition.
hypervisor_partition_attached_devices = Gauge(
    subsystem='hypervisor_partition',
    name='attached_devices',
    documentation='The number of devices attached to the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of pages deposited into the partition.
hypervisor_partition_deposited_pages = Gauge(
    subsystem='hypervisor_partition',
    name='deposited_pages',
    documentation='The number of pages deposited into the partition.',
    labelnames=['hypervisor_partition'],
)
# An indicator of illegal DMA requests generated by all devices assigned to the partition.
hypervisor_partition_device_dma_errors = Gauge(
    subsystem='hypervisor_partition',
    name='device_dma_errors',
    documentation='An indicator of illegal DMA requests generated by all devices assigned to the partition.',
    labelnames=['hypervisor_partition'],
)
# An indicator of illegal interrupt requests generated by all devices assigned to the partition.
hypervisor_partition_device_interrupt_errors = Gauge(
    subsystem='hypervisor_partition',
    name='device_interrupt_errors',
    documentation='An indicator of illegal interrupt requests generated by all devices assigned to the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of device interrupt mappings used by the partition.
hypervisor_partition_device_interrupt_mappings = Gauge(
    subsystem='hypervisor_partition',
    name='device_interrupt_mappings',
    documentation='The number of device interrupt mappings used by the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of times an interrupt from a device assigned to the partition was temporarily throttled because the device was generating too many interrupts.
hypervisor_partition_device_interrupt_throttle_events = Gauge(
    subsystem='hypervisor_partition',
    name='device_interrupt_throttle_events',
    documentation='The number of times an interrupt from a device assigned to the partition was temporarily throttled because the device was generating too many interrupts.',
    labelnames=['hypervisor_partition'],
)
# The number of pages present in the GPA space of the partition (zero for root partition)..
hypervisor_partition_gpa_pages = Gauge(
    subsystem='hypervisor_partition',
    name='gpa_pages',
    documentation='The number of pages present in the GPA space of the partition (zero for root partition).',
    labelnames=['hypervisor_partition'],
)
# The rate of modifications to the GPA space of the partition.
hypervisor_partition_gpa_space_modifications = Gauge(
    subsystem='hypervisor_partition',
    name='gpa_space_modifications',
    documentation='The rate of modifications to the GPA space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The average time (in nanoseconds) spent processing an I/O TLB flush.
hypervisor_partition_io_tlb_flush_cost = Gauge(
    subsystem='hypervisor_partition',
    name='io_tlb_flush_cost',
    documentation='The average time (in nanoseconds) spent processing an I/O TLB flush.',
    labelnames=['hypervisor_partition'],
)
# The rate of flushes of I/O TLBs of the partition.
hypervisor_partition_io_tlb_flushes_persec = Gauge(
    subsystem='hypervisor_partition',
    name='io_tlb_flushes_persec',
    documentation='The rate of flushes of I/O TLBs of the partition.',
    labelnames=['hypervisor_partition'],
)
# The recommended number of pages to be deposited for the virtual TLB.
hypervisor_partition_recommended_virtual_tlb_size = Gauge(
    subsystem='hypervisor_partition',
    name='recommended_virtual_tlb_size',
    documentation='The recommended number of pages to be deposited for the virtual TLB.',
    labelnames=['hypervisor_partition'],
)
# The number of timer interrupts skipped for the partition.
hypervisor_partition_skipped_timer_ticks = Gauge(
    subsystem='hypervisor_partition',
    name='skipped_timer_ticks',
    documentation='The number of timer interrupts skipped for the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 1G pages present in the device space of the partition.
hypervisor_partition_value_1G_device_pages = Gauge(
    subsystem='hypervisor_partition',
    name='value_1G_device_pages',
    documentation='The number of 1G pages present in the device space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 1G pages present in the GPA space of the partition.
hypervisor_partition_value_1G_gpa_pages = Gauge(
    subsystem='hypervisor_partition',
    name='1G_gpa_pages',
    documentation='The number of 1G pages present in the GPA space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 2M pages present in the device space of the partition.
hypervisor_partition_value_2M_device_pages = Gauge(
    subsystem='hypervisor_partition',
    name='value_2M_device_pages',
    documentation='The number of 2M pages present in the device space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 2M pages present in the GPA space of the partition.
hypervisor_partition_value_2M_gpa_pages = Gauge(
    subsystem='hypervisor_partition',
    name='value_2M_gpa_pages',
    documentation='The number of 2M pages present in the GPA space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 4K pages present in the device space of the partition.
hypervisor_partition_value_4K_device_pages = Gauge(
    subsystem='hypervisor_partition',
    name='value_4K_device_pages',
    documentation='The number of 4K pages present in the device space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of 4K pages present in the GPA space of the partition.
hypervisor_partition_value_4K_gpa_pages = Gauge(
    subsystem='hypervisor_partition',
    name='value_4K_gpa_pages',
    documentation='The number of 4K pages present in the GPA space of the partition.',
    labelnames=['hypervisor_partition'],
)
# The number of virtual processors present in the partition.
hypervisor_partition_virtual_processors = Gauge(
    subsystem='hypervisor_partition',
    name='virtual_processors',
    documentation='The number of virtual processors present in the partition.',
    labelnames=['hypervisor_partition'],
)
# The rate of flushes of the entire virtual TLB.
hypervisor_partition_virtual_tlb_flush_entires_persec = Gauge(
    subsystem='hypervisor_partition',
    name='virtual_tlb_flush_entires_persec',
    documentation='The rate of flushes of the entire virtual TLB.',
    labelnames=['hypervisor_partition'],
)
# The number of pages used by the virtual TLB of the partition.
hypervisor_partition_virtual_tlb_pages = Gauge(
    subsystem='hypervisor_partition',
    name='virtual_tlb_pages',
    documentation='The number of pages used by the virtual TLB of the partition.',
    labelnames=['hypervisor_partition'],
)

# HvStats_HyperVHypervisorRootPartition
# The number of address spaces in the virtual TLB of the partition.
hypervisor_root_partition_address_spaces = Gauge(
    subsystem='hypervisor_root_partition',
    name='address_spaces',
    documentation='The number of address spaces in the virtual TLB of the partition.',
    labelnames=['hypervisor'],
)
# The number of devices attached to the partition.
hypervisor_root_partition_attached_devices = Gauge(
    subsystem='hypervisor_root_partition',
    name='attached_devices',
    documentation='The number of devices attached to the partition.',
    labelnames=['hypervisor'],
)
# The number of pages deposited into the partition.
hypervisor_root_partition_deposited_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='deposited_pages',
    documentation='The number of pages deposited into the partition.',
    labelnames=['hypervisor'],
)
# An indicator of illegal DMA requests generated by all devices assigned to the partition.
hypervisor_root_partition_device_dma_errors = Gauge(
    subsystem='hypervisor_root_partition',
    name='device_dma_errors',
    documentation='An indicator of illegal DMA requests generated by all devices assigned to the partition.',
    labelnames=['hypervisor'],
)
# An indicator of illegal interrupt requests generated by all devices assigned to the partition.
hypervisor_root_partition_device_interrupt_errors = Gauge(
    subsystem='hypervisor_root_partition',
    name='device_interrupt_errors',
    documentation='An indicator of illegal interrupt requests generated by all devices assigned to the partition.',
    labelnames=['hypervisor'],
)
# The number of device interrupt mappings used by the partition.
hypervisor_root_partition_device_interrupt_mappings = Gauge(
    subsystem='hypervisor_root_partition',
    name='device_interrupt_mappings',
    documentation='The number of device interrupt mappings used by the partition.',
    labelnames=['hypervisor'],
)
# The number of times an interrupt from a device assigned to the partition was temporarily throttled because the device was generating too many interrupts.
hypervisor_root_partition_device_interrupt_throttle_events = Gauge(
    subsystem='hypervisor_root_partition',
    name='device_interrupt_throttle_events',
    documentation='The number of times an interrupt from a device assigned to the partition was temporarily throttled because the device was generating too many interrupts.',
    labelnames=['hypervisor'],
)
# The number of pages present in the GPA space of the partition (zero for root partition)..
hypervisor_root_partition_gpa_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='gpa_pages',
    documentation='The number of pages present in the GPA space of the partition (zero for root partition).',
    labelnames=['hypervisor'],
)
# The rate of modifications to the GPA space of the partition.
hypervisor_root_partition_gpa_space_modifications = Gauge(
    subsystem='hypervisor_root_partition',
    name='gpa_space_modifications',
    documentation='The rate of modifications to the GPA space of the partition.',
    labelnames=['hypervisor'],
)
# The average time (in nanoseconds) spent processing an I/O TLB flush.
hypervisor_root_partition_io_tlb_flush_cost = Gauge(
    subsystem='hypervisor_root_partition',
    name='io_tlb_flush_cost',
    documentation='The average time (in nanoseconds) spent processing an I/O TLB flush.',
    labelnames=['hypervisor'],
)
# The rate of flushes of I/O TLBs of the partition.
hypervisor_root_partition_io_tlb_flushes_persec = Gauge(
    subsystem='hypervisor_root_partition',
    name='io_tlb_flushes_persec',
    documentation='The rate of flushes of I/O TLBs of the partition.',
    labelnames=['hypervisor'],
)
# The recommended number of pages to be deposited for the virtual TLB.
hypervisor_root_partition_recommended_virtual_tlb_size = Gauge(
    subsystem='hypervisor_root_partition',
    name='recommended_virtual_tlb_size',
    documentation='The recommended number of pages to be deposited for the virtual TLB.',
    labelnames=['hypervisor'],
)
# The number of timer interrupts skipped for the partition.
hypervisor_root_partition_skipped_timer_ticks = Gauge(
    subsystem='hypervisor_root_partition',
    name='skipped_timer_ticks',
    documentation='The number of timer interrupts skipped for the partition.',
    labelnames=['hypervisor'],
)
# The number of 1G pages present in the device space of the partition.
hypervisor_root_partition_value_1G_device_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='value_1G_device_pages',
    documentation='The number of 1G pages present in the device space of the partition.',
    labelnames=['hypervisor'],
)
# The number of 1G pages present in the GPA space of the partition.
hypervisor_root_partition_value_1G_gpa_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='1G_gpa_pages',
    documentation='The number of 1G pages present in the GPA space of the partition.',
    labelnames=['hypervisor'],
)
# The number of 2M pages present in the device space of the partition.
hypervisor_root_partition_value_2M_device_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='value_2M_device_pages',
    documentation='The number of 2M pages present in the device space of the partition.',
    labelnames=['hypervisor'],
)
# The number of 2M pages present in the GPA space of the partition.
hypervisor_root_partition_value_2M_gpa_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='value_2M_gpa_pages',
    documentation='The number of 2M pages present in the GPA space of the partition.',
    labelnames=['hypervisor'],
)
# The number of 4K pages present in the device space of the partition.
hypervisor_root_partition_value_4K_device_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='value_4K_device_pages',
    documentation='The number of 4K pages present in the device space of the partition.',
    labelnames=['hypervisor'],
)
# The number of 4K pages present in the GPA space of the partition.
hypervisor_root_partition_value_4K_gpa_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='value_4K_gpa_pages',
    documentation='The number of 4K pages present in the GPA space of the partition.',
    labelnames=['hypervisor'],
)
# The number of virtual processors present in the partition.
hypervisor_root_partition_virtual_processors = Gauge(
    subsystem='hypervisor_root_partition',
    name='virtual_processors',
    documentation='The number of virtual processors present in the partition.',
    labelnames=['hypervisor'],
)
# The rate of flushes of the entire virtual TLB.
hypervisor_root_partition_virtual_tlb_flush_entires_persec = Gauge(
    subsystem='hypervisor_root_partition',
    name='virtual_tlb_flush_entires_persec',
    documentation='The rate of flushes of the entire virtual TLB.',
    labelnames=['hypervisor'],
)
# The number of pages used by the virtual TLB of the partition.
hypervisor_root_partition_virtual_tlb_pages = Gauge(
    subsystem='hypervisor_root_partition',
    name='virtual_tlb_pages',
    documentation='The number of pages used by the virtual TLB of the partition.',
    labelnames=['hypervisor'],
)

# Win32_PerfFormattedData_HvStats_HyperVHypervisor
# The number of logical processors present in the system.
hypervisor_logical_processors = Gauge(
    subsystem='hypervisor',
    name='logical_processors',
    documentation='The number of logical processors present in the system.'
)
# The number of monitored notifications registered with the hypervisor.
hypervisor_monitored_notifications = Gauge(
    subsystem='hypervisor',
    name='monitored_notifications',
    documentation='The number of monitored notifications registered with the hypervisor.'
)
# The number of partitions (virtual machines) present in the system.
hypervisor_partitions = Gauge(
    subsystem='hypervisor',
    name='partitions',
    documentation='The number of partitions (virtual machines) present in the system.'
)
# The number of bootstrap and deposited pages in the hypervisor.
hypervisor_total_pages = Gauge(
    subsystem='hypervisor',
    name='total_pages',
    documentation='The number of bootstrap and deposited pages in the hypervisor.'
)
# The number of virtual processors present in the system.
hypervisor_virtual_processors = Gauge(
    subsystem='hypervisor',
    name='virtual_processors',
    documentation='The number of virtual processors present in the system.'
)

# HvStats_HyperVHypervisorRootVirtualProcessor
# The percentage of time spent by the virtual processor in guest code.
hypervisor_root_virtual_processor_percent_guest_run_time = Gauge(
    subsystem='hypervisor_root_virtual_processor',
    name='guest_run_time',
    documentation='The percentage of time spent by the virtual processor in guest code.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor in hypervisor code.
hypervisor_root_virtual_processor_percent_hypervisor_run_time = Gauge(
    subsystem='hypervisor_root_virtual_processor',
    name='percent_hypervisor_run_time',
    documentation='The percentage of time spent by the virtual processor in hypervisor code.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor running on a remote node.
hypervisor_root_virtual_processor_percent_remote_run_time = Gauge(
    subsystem='hypervisor_root_virtual_processor',
    name='percent_remote_run_time',
    documentation='The percentage of time spent by the virtual processor running on a remote node.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor in guest and hypervisor code.
hypervisor_root_virtual_processor_percent_total_run_time = Gauge(
    subsystem='hypervisor_root_virtual_processor',
    name='percent_total_run_time',
    documentation='The percentage of time spent by the virtual processor in guest and hypervisor code.',
    labelnames=['vp'],
)

# HvStats_HyperVHypervisorVirtualProcessor
# The percentage of time spent by the virtual processor in guest code.
hypervisor_virtual_processor_percent_guest_run_time = Gauge(
    subsystem='hypervisor_virtual_processor',
    name='guest_run_time',
    documentation='The percentage of time spent by the virtual processor in guest code.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor in hypervisor code.
hypervisor_virtual_processor_percent_hypervisor_run_time = Gauge(
    subsystem='hypervisor_virtual_processor',
    name='percent_hypervisor_run_time',
    documentation='The percentage of time spent by the virtual processor in hypervisor code.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor running on a remote node.
hypervisor_virtual_processor_percent_remote_run_time = Gauge(
    subsystem='hypervisor_virtual_processor',
    name='percent_remote_run_time',
    documentation='The percentage of time spent by the virtual processor running on a remote node.',
    labelnames=['vp'],
)
# The percentage of time spent by the virtual processor in guest and hypervisor code.
hypervisor_virtual_processor_percent_total_run_time = Gauge(
    subsystem='hypervisor_virtual_processor',
    name='percent_total_run_time',
    documentation='The percentage of time spent by the virtual processor in guest and hypervisor code.',
    labelnames=['vp'],
)

# BalancerStats_HyperVDynamicMemoryVM
# This counter represents the average pressure in the VM.
dynamic_memory_vm_average_pressure = Gauge(
    subsystem='dynamic_memory_vm',
    name='average_pressure',
    documentation='This counter represents the average pressure in the VM.',
    labelnames=['vm'],
)
# This counter represents the current pressure in the VM.
dynamic_memory_vm_current_pressure = Gauge(
    subsystem='dynamic_memory_vm',
    name='current_pressure',
    documentation='This counter represents the current pressure in the VM.',
    labelnames=['vm'],
)
# This counter represents the amount of memory visible in the VM.
dynamic_memory_vm_guest_visible_physical_memory = Gauge(
    subsystem='dynamic_memory_vm',
    name='guest_visible_physical_memory',
    documentation='This counter represents the amount of memory visible in the VM.',
    labelnames=['vm'],
)
# This counter represents the maximum pressure band in the VM.
dynamic_memory_vm_maximum_pressure = Gauge(
    subsystem='dynamic_memory_vm',
    name='maximum_pressure',
    documentation='This counter represents the maximum pressure band in the VM.',
    labelnames=['vm'],
)
dynamic_memory_vm_minimum_pressure = Gauge(
    subsystem='dynamic_memory_vm',
    name='minimum_pressure',
    documentation='This counter represents the minimum pressure band in the VM.',
    labelnames=['vm'],
)
# This counter represents the current amount of memory in the VM.
dynamic_memory_vm_physical_memory = Gauge(
    subsystem='dynamic_memory_vm',
    name='physical_memory',
    documentation='This counter represents the current amount of memory in the VM.',
    labelnames=['vm'],
)
# Size of memory backed by Smart Paging in Mbytes.
dynamic_memory_vm_smart_paging_working_set_size = Gauge(
    subsystem='dynamic_memory_vm',
    name='smart_paging_working_set_size',
    documentation='Size of memory backed by Smart Paging in Mbytes.',
    labelnames=['vm'],
)

# BalancerStats_HyperVDynamicMemoryBalancer
# This counter represents the amount of memory left on the node.
dynamic_memory_balancer_available_memory = Gauge(
    subsystem='dynamic_memory_balancer',
    name='available_memory',
    documentation='This counter represents the amount of memory left on the node.'
)
# This counter represents the average system pressure on the balancer node among all balanced objects.
dynamic_memory_balancer_average_pressure = Gauge(
    subsystem='dynamic_memory_balancer',
    name='average_pressure',
    documentation='This counter represents the average system pressure on the balancer node among all balanced objects.'
)

# Counters_HyperVVirtualStorageDevice
# This counter represents the total number of errors that have occurred on this virtual device.
virtual_storage_device_error_count = Counter(
    subsystem='virtual_storage_device',
    name='error_count',
    documentation='This counter represents the total number of errors that have occurred on this virtual device.',
    labelnames=['device'],
)
# This counter represents the total number of flush operations that have occurred on this virtual device.
virtual_storage_device_flush_count = Counter(
    subsystem='virtual_storage_device',
    name='flush_count',
    documentation='This counter represents the total number of flush operations that have occurred on this virtual device.',
    labelnames=['device'],
)
# This counter represents the average number of 8KB IO transfers per second completed by this virtual device.
virtual_storage_device_normalized_throughput = Gauge(
    subsystem='virtual_storage_device',
    name='normalized_throughput',
    documentation='This counter represents the average number of 8KB IO transfers per second completed by this virtual device.',
    labelnames=['device'],
)
# This counter represents the current queue length on this virtual device.
virtual_storage_device_queue_length = Gauge(
    subsystem='virtual_storage_device',
    name='queue_length',
    documentation='This counter represents the current queue length on this virtual device.',
    labelnames=['device'],
)
# This counter represents the IO quota replenishment rate for this virtual device.
virtual_storage_device_io_quota_replenishment_rate = Gauge(
    subsystem='virtual_storage_device',
    name='io_quota_replenishment_rate',
    documentation='This counter represents the IO quota replenishment rate for this virtual device.',
    labelnames=['device'],
)
# This counter represents the total number of bytes that have been read per second on this virtual device.
virtual_storage_device_read_bytes_persec = Gauge(
    subsystem='virtual_storage_device',
    name='read_bytes_persec',
    documentation='This counter represents the total number of bytes that have been read per second on this virtual device.',
    labelnames=['device'],
)
# This counter represents the total number of read operations that have occurred on this virtual device.
virtual_storage_device_read_count = Counter(
    subsystem='virtual_storage_device',
    name='read_count',
    documentation='This counter represents the total number of read operations that have occurred on this virtual device.',
    labelnames=['device'],
)
# This counter represents the number of read operations that have occurred per second on this virtual device.
virtual_storage_device_read_operations_persec = Gauge(
    subsystem='virtual_storage_device',
    name='read_operations_persec',
    documentation='This counter represents the number of read operations that have occurred per second on this virtual device.',
    labelnames=['device'],
)

# This counter represents the total number of bytes that have been written per second on this virtual device.
virtual_storage_device_write_bytes_persec = Gauge(
    subsystem='virtual_storage_device',
    name='write_bytes_persec',
    documentation='This counter represents the total number of bytes that have been written per second on this virtual device.',
    labelnames=['device'],
)
# This counter represents the total number of write operations that have occurred on this virtual device.
virtual_storage_device_write_count = Gauge(
    subsystem='virtual_storage_device',
    name='write_count',
    documentation='This counter represents the total number of write operations that have occurred on this virtual device.',
    labelnames=['device'],
)

# This counter represents the number of write operations that have occurred per second on this virtual device.
virtual_storage_device_write_operations_persec = Gauge(
    subsystem='virtual_storage_device',
    name='write_operations_persec',
    documentation='This counter represents the number of write operations that have occurred per second on this virtual device.',
    labelnames=['device'],
)

# Counters_HyperVVirtualMachineBus
# This counter represents the rate of interrupts received.
virtual_machine_bus_interrupts_received_persec = Gauge(
    subsystem='virtual_machine_bus',
    name='interrupts_received_persec',
    documentation='This counter represents the rate of interrupts received.',
)
# This counter represents the rate of interrupts sent.
virtual_machine_bus_interrupts_sent_persec = Gauge(
    subsystem='virtual_machine_bus',
    name='interrupts_sent_persec',
    documentation='This counter represents the rate of interrupts sent.',
)
# This counter represents the total number of times that any partition has been throttled, which is to say that its interrupts were disabled.
virtual_machine_bus_throttle_events = Counter(
    subsystem='virtual_machine_bus',
    name='throttle_events',
    documentation='This counter represents the total number of times that any partition has been throttled, which is to say that its interrupts were disabled.',
)

# NvspNicStats_HyperVVirtualNetworkAdapter
# This counter represents the total number of broadcast packets received per second by the network adapter.
virtual_network_adapter_broadcast_packets_received_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='broadcast_packets_received_persec',
    documentation='This counter represents the total number of broadcast packets received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of broadcast packets sent per second by the network adapter.
virtual_network_adapter_broadcast_packets_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='broadcast_packets_sent_persec',
    documentation='This counter represents the total number of broadcast packets sent per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of bytes per second traversing the network adapter.
virtual_network_adapter_bytes_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='bytes_persec',
    documentation='This counter represents the total number of bytes per second traversing the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of bytes received per second by the network adapter.
virtual_network_adapter_bytes_received_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='bytes_received_persec',
    documentation='This counter represents the total number of bytes received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of bytes sent per second by the network adapter.
virtual_network_adapter_bytes_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='bytes_sent_persec',
    documentation='This counter represents the total number of bytes sent per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of directed packets received per second by the network adapter.
virtual_network_adapter_directed_packets_received_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='directed_packets_received_persec',
    documentation='This counter represents the total number of directed packets received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of directed packets sent per second by the network adapter.
virtual_network_adapter_directed_packets_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='directed_packets_sent_persec',
    documentation='This counter represents the total number of directed packets sent per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of dropped packets per second in the incoming direction of the network adapter.
virtual_network_adapter_dropped_packets_incoming_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='dropped_packets_incoming_persec',
    documentation='This counter represents the total number of dropped packets per second in the incoming direction of the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of dropped packets per second in the outgoing direction of the network adapter.
virtual_network_adapter_dropped_packets_outgoing_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='dropped_packets_outgoing_persec',
    documentation='This counter represents the total number of dropped packets per second in the outgoing direction of the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of dropped packets per second by switch extensions in the incoming direction of the network adapter.
virtual_network_adapter_extensions_dropped_packets_incoming_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='extensions_dropped_packets_incoming_persec',
    documentation='This counter represents the total number of dropped packets per second by switch extensions in the incoming direction of the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of dropped packets per second by switch extensions in the outgoing direction of the network adapter.
virtual_network_adapter_extensions_dropped_packets_outgoing_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='extensions_dropped_packets_outgoing_persec',
    documentation='This counter represents the total number of dropped packets per second by switch extensions in the outgoing direction of the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of Psec offload bytes received per second by the network adapter.
virtual_network_adapter_i_psecoffload_bytes_receive_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='i_psecoffload_bytes_receive_persec',
    documentation='This counter represents the total number of Psec offload bytes received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of Psec offload bytes sent per second by the network adapter.
virtual_network_adapter_i_psecoffload_bytes_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='i_psecoffload_bytes_sent_persec',
    documentation='This counter represents the total number of Psec offload bytes sent per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of multicast packets received per second by the network adapter.
virtual_network_adapter_multicast_packets_received_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='multicast_packets_received_persec',
    documentation='This counter represents the total number of multicast packets received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of multicast packets sent per second by the network adapter.
virtual_network_adapter_multicast_packets_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='multicast_packets_sent_persec',
    documentation='This counter represents the total number of multicast packets sent per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of packets per second traversing the network adapter.
virtual_network_adapter_packets_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='packets_persec',
    documentation='This counter represents the total number of packets per second traversing the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of packets received per second by the network adapter.
virtual_network_adapter_packets_received_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='packets_received_persec',
    documentation='This counter represents the total number of packets received per second by the network adapter.',
    labelnames=['adapter'],
)
# This counter represents the total number of packets sent per second by the network adapter.
virtual_network_adapter_packets_sent_persec = Gauge(
    subsystem='virtual_network_adapter',
    name='packets_sent_persec',
    documentation='This counter represents the total number of packets sent per second by the network adapter.',
    labelnames=['adapter'],
)

# Win32_PerfFormattedData_NvspSwitchStats_HyperVVirtualSwitch
# This counter represents the total number of broadcast packets received per second by the virtual switch.
virtual_switch_broadcast_packets_received_persec = Gauge(
    subsystem='virtual_switch',
    name='broadcast_packets_received_persec',
    documentation='This counter represents the total number of broadcast packets received per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of broadcast packets sent per second by the virtual switch.
virtual_switch_broadcast_packets_sent_persec = Gauge(
    subsystem='virtual_switch',
    name='broadcast_packets_sent_persec',
    documentation='This counter represents the total number of broadcast packets sent per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of bytes per second traversing the virtual switch.
virtual_switch_bytes_persec = Gauge(
    subsystem='virtual_switch',
    name='bytes_persec',
    documentation='This counter represents the total number of bytes per second traversing the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of bytes received per second by the virtual switch.
virtual_switch_bytes_received_persec = Gauge(
    subsystem='virtual_switch',
    name='bytes_received_persec',
    documentation='This counter represents the total number of bytes received per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of bytes sent per second by the virtual switch
virtual_switch_bytes_sent_persec = Gauge(
    subsystem='virtual_switch',
    name='bytes_sent_persec',
    documentation='This counter represents the total number of bytes sent per second by the virtual switch',
    labelnames=['vswitch'],
)
# This counter represents the total number of directed packets received per second by the virtual switch.
virtual_switch_directed_packets_received_persec = Gauge(
    subsystem='virtual_switch',
    name='directed_packets_received_persec',
    documentation='This counter represents the total number of directed packets received per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of directed packets sent per second by the virtual switch.
virtual_switch_directed_packets_sent_persec = Gauge(
    subsystem='virtual_switch',
    name='directed_packets_sent_persec',
    documentation='This counter represents the total number of directed packets sent per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packet dropped per second by the virtual switch in the incoming direction.
virtual_switch_dropped_packets_incoming_persec = Gauge(
    subsystem='virtual_switch',
    name='dropped_packets_incoming_persec',
    documentation='This counter represents the total number of packet dropped per second by the virtual switch in the incoming direction.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packet dropped per second by the virtual switch in the outgoing direction.
virtual_switch_dropped_packets_outgoing_persec = Gauge(
    subsystem='virtual_switch',
    name='dropped_packets_outgoing_persec',
    documentation='This counter represents the total number of packet dropped per second by the virtual switch in the outgoing direction.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packet dropped per second by the virtual switch extensions in the incoming direction.
virtual_switch_extensions_dropped_packets_incoming_persec = Gauge(
    subsystem='virtual_switch',
    name='extensions_dropped_packets_incoming_persec',
    documentation='This counter represents the total number of packet dropped per second by the virtual switch extensions in the incoming direction.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packet dropped per second by the virtual switch extensions in the outgoing direction.
virtual_switch_extensions_dropped_packets_outgoing_persec = Gauge(
    subsystem='virtual_switch',
    name='extensions_dropped_packets_outgoing_persec',
    documentation='This counter represents the total number of packet dropped per second by the virtual switch extensions in the outgoing direction.',
    labelnames=['vswitch'],
)
# This counter represents the total number of learned MAC addresses of the virtual switch.
virtual_switch_learned_mac_addresses = Gauge(
    subsystem='virtual_switch',
    name='learned_mac_addresses',
    documentation='This counter represents the total number of learned MAC addresses of the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number MAC addresses learned per second by the virtual switch.
virtual_switch_learned_mac_addresses_persec = Gauge(
    subsystem='virtual_switch',
    name='learned_mac_addresses_persec',
    documentation='This counter represents the total number MAC addresses learned per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of multicast packets received per second by the virtual switch.
virtual_switch_multicast_packets_received_persec = Gauge(
    subsystem='virtual_switch',
    name='multicast_packets_received_persec',
    documentation='This counter represents the total number of multicast packets received per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of multicast packets sent per second by the virtual switch.
virtual_switch_multicast_packets_sent_persec = Gauge(
    subsystem='virtual_switch',
    name='multicast_packets_sent_persec',
    documentation='This counter represents the total number of multicast packets sent per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of send channel moves per second on this virtual switch.
virtual_switch_numberof_send_channel_moves_persec = Gauge(
    subsystem='virtual_switch',
    name='numberof_send_channel_moves_persec',
    documentation='This counter represents the total number of send channel moves per second on this virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of VMQ moves per second on this virtual switch.
virtual_switch_numberof_vmq_moves_persec = Gauge(
    subsystem='virtual_switch',
    name='numberof_vmq_moves_persec',
    documentation='This counter represents the total number of VMQ moves per second on this virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packets flooded by the virtual switch.
virtual_switch_packets_flooded = Counter(
    subsystem='virtual_switch',
    name='packets_flooded',
    documentation='This counter represents the total number of packets flooded by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packets flooded per second by the virtual switch.
virtual_switch_packets_flooded_persec = Gauge(
    subsystem='virtual_switch',
    name='packets_flooded_persec',
    documentation='This counter represents the total number of packets flooded per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packets per second traversing the virtual switch.
virtual_switch_packets_persec = Gauge(
    subsystem='virtual_switch',
    name='packets_persec',
    documentation='This counter represents the total number of packets per second traversing the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packets received per second by the virtual switch.
virtual_switch_packets_received_persec = Gauge(
    subsystem='virtual_switch',
    name='packets_received_persec',
    documentation='This counter represents the total number of packets received per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of packets sent per second by the virtual switch.
virtual_switch_packets_sent_persec = Gauge(
    subsystem='virtual_switch',
    name='packets_sent_persec',
    documentation='This counter represents the total number of packets sent per second by the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number of purged MAC addresses of the virtual switch.
virtual_switch_purged_mac_addresses = Gauge(
    subsystem='virtual_switch',
    name='purged_mac_addresses',
    documentation='This counter represents the total number of purged MAC addresses of the virtual switch.',
    labelnames=['vswitch'],
)
# This counter represents the total number MAC addresses purged per second by the virtual switch.
virtual_switch_purged_mac_addresses_persec = Gauge(
    subsystem='virtual_switch',
    name='purged_mac_addresses_persec',
    documentation='This counter represents the total number MAC addresses purged per second by the virtual switch.',
    labelnames=['vswitch'],
)


def update_metrics():
    hyper_v_virtual_machine_summary = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_VmmsVirtualMachineStats_HyperVVirtualMachineHealthSummary')
    for virtual_machine_summary in hyper_v_virtual_machine_summary:
        virtual_machine_health_summary_health_critical.set(virtual_machine_summary.HealthCritical)
        virtual_machine_health_summary_health_ok.set(virtual_machine_summary.HealthOk)

    hyper_v_vid_partition = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_VidPerfProvider_HyperVVMVidPartition')
    for vid_partition in hyper_v_vid_partition:
        vm_vid_partition_physical_pages_allocated \
            .labels(vm=vid_partition.Name) \
            .set(vid_partition.PhysicalPagesAllocated)
        vm_vid_partition_preferred_numa_node_index \
            .labels(vm=vid_partition.Name) \
            .set(vid_partition.PreferredNUMANodeIndex)
        vm_vid_partition_remote_physical_pages \
            .labels(vm=vid_partition.Name) \
            .set(vid_partition.RemotePhysicalPages)

    hyper_v_partition = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_HvStats_HyperVHypervisorPartition')
    for partition in hyper_v_partition:
        hypervisor_partition_address_spaces \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.AddressSpaces)
        hypervisor_partition_attached_devices \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.AttachedDevices)
        hypervisor_partition_deposited_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.DepositedPages)
        hypervisor_partition_device_dma_errors \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.DeviceDMAErrors)
        hypervisor_partition_device_interrupt_errors \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.DeviceInterruptErrors)
        hypervisor_partition_device_interrupt_mappings \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.DeviceInterruptMappings)
        hypervisor_partition_device_interrupt_throttle_events \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.DeviceInterruptThrottleEvents)
        hypervisor_partition_gpa_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.GPAPages)
        hypervisor_partition_gpa_space_modifications \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.GPASpaceModificationsPersec)
        hypervisor_partition_io_tlb_flush_cost \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.IOTLBFlushCost)
        hypervisor_partition_io_tlb_flushes_persec \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.IOTLBFlushesPersec)
        hypervisor_partition_recommended_virtual_tlb_size \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.RecommendedVirtualTLBSize)
        hypervisor_partition_skipped_timer_ticks \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.SkippedTimerTicks)
        hypervisor_partition_value_1G_device_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value1GDevicePages)
        hypervisor_partition_value_1G_gpa_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value1GGPAPages)
        hypervisor_partition_value_2M_device_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value2MDevicePages)
        hypervisor_partition_value_2M_gpa_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value2MGPAPages)
        hypervisor_partition_value_4K_device_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value4KDevicePages)
        hypervisor_partition_value_4K_gpa_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.Value4KGPAPages)
        hypervisor_partition_virtual_processors \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.VirtualProcessors)
        hypervisor_partition_virtual_tlb_flush_entires_persec \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.VirtualTLBFlushEntiresPersec)
        hypervisor_partition_virtual_tlb_pages \
            .labels(hypervisor_partition=partition.Name) \
            .set(partition.VirtualTLBPages)

    hyper_v_root_partition = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_HvStats_HyperVHypervisorRootPartition')
    for partition in hyper_v_root_partition:
        hypervisor_root_partition_address_spaces \
            .labels(hypervisor=partition.Name) \
            .set(partition.AddressSpaces)
        hypervisor_root_partition_attached_devices \
            .labels(hypervisor=partition.Name) \
            .set(partition.AttachedDevices)
        hypervisor_root_partition_deposited_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.DepositedPages)
        hypervisor_root_partition_device_dma_errors \
            .labels(hypervisor=partition.Name) \
            .set(partition.DeviceDMAErrors)
        hypervisor_root_partition_device_interrupt_errors \
            .labels(hypervisor=partition.Name) \
            .set(partition.DeviceInterruptErrors)
        hypervisor_root_partition_device_interrupt_mappings \
            .labels(hypervisor=partition.Name) \
            .set(partition.DeviceInterruptMappings)
        hypervisor_root_partition_device_interrupt_throttle_events \
            .labels(hypervisor=partition.Name) \
            .set(partition.DeviceInterruptThrottleEvents)
        hypervisor_root_partition_gpa_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.GPAPages)
        hypervisor_root_partition_gpa_space_modifications \
            .labels(hypervisor=partition.Name) \
            .set(partition.GPASpaceModificationsPersec)
        hypervisor_root_partition_io_tlb_flush_cost \
            .labels(hypervisor=partition.Name) \
            .set(partition.IOTLBFlushCost)
        hypervisor_root_partition_io_tlb_flushes_persec \
            .labels(hypervisor=partition.Name) \
            .set(partition.IOTLBFlushesPersec)
        hypervisor_root_partition_recommended_virtual_tlb_size \
            .labels(hypervisor=partition.Name) \
            .set(partition.RecommendedVirtualTLBSize)
        hypervisor_root_partition_skipped_timer_ticks \
            .labels(hypervisor=partition.Name) \
            .set(partition.SkippedTimerTicks)
        hypervisor_root_partition_value_1G_device_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value1GDevicePages)
        hypervisor_root_partition_value_1G_gpa_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value1GGPAPages)
        hypervisor_root_partition_value_2M_device_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value2MDevicePages)
        hypervisor_root_partition_value_2M_gpa_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value2MGPAPages)
        hypervisor_root_partition_value_4K_device_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value4KDevicePages)
        hypervisor_root_partition_value_4K_gpa_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.Value4KGPAPages)
        hypervisor_root_partition_virtual_processors \
            .labels(hypervisor=partition.Name) \
            .set(partition.VirtualProcessors)
        hypervisor_root_partition_virtual_tlb_flush_entires_persec \
            .labels(hypervisor=partition.Name) \
            .set(partition.VirtualTLBFlushEntiresPersec)
        hypervisor_root_partition_virtual_tlb_pages \
            .labels(hypervisor=partition.Name) \
            .set(partition.VirtualTLBPages)

    hyper_v_hypervisor = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_HvStats_HyperVHypervisor')
    for hypervisor in hyper_v_hypervisor:
        hypervisor_logical_processors \
            .set(hypervisor.LogicalProcessors)
        hypervisor_monitored_notifications \
            .set(hypervisor.MonitoredNotifications)
        hypervisor_partitions \
            .set(hypervisor.Partitions)
        hypervisor_total_pages \
            .set(hypervisor.TotalPages)
        hypervisor_virtual_processors \
            .set(hypervisor.VirtualProcessors)

    hyper_v_hypervisor_root_virtual_processor = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_HvStats_HyperVHypervisorRootVirtualProcessor')
    for root_virtual_processor in hyper_v_hypervisor_root_virtual_processor:
        hypervisor_root_virtual_processor_percent_guest_run_time \
            .labels(vp=root_virtual_processor.Name) \
            .set(root_virtual_processor.PercentGuestRunTime)
        hypervisor_root_virtual_processor_percent_hypervisor_run_time \
            .labels(vp=root_virtual_processor.Name) \
            .set(root_virtual_processor.PercentHypervisorRunTime)
        hypervisor_root_virtual_processor_percent_remote_run_time \
            .labels(vp=root_virtual_processor.Name) \
            .set(root_virtual_processor.PercentRemoteRunTime)
        hypervisor_root_virtual_processor_percent_total_run_time \
            .labels(vp=root_virtual_processor.Name) \
            .set(root_virtual_processor.PercentTotalRunTime)

    hyper_v_hypervisor_virtual_processor = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_HvStats_HyperVHypervisorVirtualProcessor')
    for virtual_processor in hyper_v_hypervisor_virtual_processor:
        hypervisor_virtual_processor_percent_guest_run_time \
            .labels(vp=virtual_processor.Name) \
            .set(virtual_processor.PercentGuestRunTime)
        hypervisor_virtual_processor_percent_hypervisor_run_time \
            .labels(vp=virtual_processor.Name) \
            .set(virtual_processor.PercentHypervisorRunTime)
        hypervisor_virtual_processor_percent_remote_run_time \
            .labels(vp=virtual_processor.Name) \
            .set(virtual_processor.PercentRemoteRunTime)
        hypervisor_virtual_processor_percent_total_run_time \
            .labels(vp=virtual_processor.Name) \
            .set(virtual_processor.PercentTotalRunTime)

    hyper_v_dynamic_memory_vm = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_BalancerStats_HyperVDynamicMemoryVM')
    for dynamic_memory_vm in hyper_v_dynamic_memory_vm:
        dynamic_memory_vm_average_pressure \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.AveragePressure)
        dynamic_memory_vm_current_pressure \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.CurrentPressure)
        dynamic_memory_vm_guest_visible_physical_memory \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.GuestVisiblePhysicalMemory)
        dynamic_memory_vm_maximum_pressure \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.MaximumPressure)
        dynamic_memory_vm_minimum_pressure \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.MinimumPressure)
        dynamic_memory_vm_physical_memory \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.PhysicalMemory)
        dynamic_memory_vm_smart_paging_working_set_size \
            .labels(vm=dynamic_memory_vm.Name) \
            .set(dynamic_memory_vm.SmartPagingWorkingSetSize)

    hyper_v_dynamic_memory_balancer = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_BalancerStats_HyperVDynamicMemoryBalancer')
    for dynamic_memory_balancer in hyper_v_dynamic_memory_balancer:
        dynamic_memory_balancer_available_memory \
            .set(dynamic_memory_balancer.AvailableMemory)
        dynamic_memory_balancer_average_pressure \
            .set(dynamic_memory_balancer.AveragePressure)

    hyper_v_virtual_storage_device = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_Counters_HyperVVirtualStorageDevice')
    for virtual_storage_device in hyper_v_virtual_storage_device:
        virtual_storage_device_error_count \
            .labels(device=virtual_storage_device.Name) \
            .inc(virtual_storage_device.ErrorCount -
                 virtual_storage_device_error_count.labels(device=virtual_storage_device.Name)._value.get())
        virtual_storage_device_flush_count \
            .labels(device=virtual_storage_device.Name) \
            .inc(virtual_storage_device.FlushCount -
                 virtual_storage_device_flush_count.labels(device=virtual_storage_device.Name)._value.get())
        virtual_storage_device_queue_length \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.QueueLength)
        virtual_storage_device_io_quota_replenishment_rate \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.IOQuotaReplenishmentRate)
        virtual_storage_device_read_bytes_persec \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.ReadBytesPersec)
        virtual_storage_device_read_count \
            .labels(device=virtual_storage_device.Name) \
            .inc(virtual_storage_device.ReadCount -
                 virtual_storage_device_read_count.labels(device=virtual_storage_device.Name)._value.get())
        virtual_storage_device_read_operations_persec \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.ReadOperationsPersec)
        virtual_storage_device_write_bytes_persec \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.WriteBytesPersec)
        virtual_storage_device_write_count \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.WriteCount)
        virtual_storage_device_write_operations_persec \
            .labels(device=virtual_storage_device.Name) \
            .set(virtual_storage_device.WriteOperationsPersec)

    hyper_v_virtual_machine_bus = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_Counters_HyperVVirtualMachineBus')
    for virtual_machine_bus in hyper_v_virtual_machine_bus:
        virtual_machine_bus_interrupts_received_persec \
            .set(virtual_machine_bus.InterruptsReceivedPersec)
        virtual_machine_bus_interrupts_sent_persec \
            .set(virtual_machine_bus.InterruptsSentPersec)
        virtual_machine_bus_throttle_events \
            .inc(float(virtual_machine_bus.ThrottleEvents) - virtual_machine_bus_throttle_events._value.get())

    hyper_v_virtual_network_adapter = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_NvspNicStats_HyperVVirtualNetworkAdapter')
    for virtual_network_adapter in hyper_v_virtual_network_adapter:
        virtual_network_adapter_broadcast_packets_received_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.BroadcastPacketsReceivedPersec)
        virtual_network_adapter_broadcast_packets_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.BroadcastPacketsSentPersec)
        virtual_network_adapter_bytes_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.BytesPersec)
        virtual_network_adapter_bytes_received_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.BytesReceivedPersec)
        virtual_network_adapter_bytes_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.BytesSentPersec)
        virtual_network_adapter_directed_packets_received_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.DirectedPacketsReceivedPersec)
        virtual_network_adapter_directed_packets_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.DirectedPacketsSentPersec)
        virtual_network_adapter_dropped_packets_incoming_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.DroppedPacketsIncomingPersec)
        virtual_network_adapter_dropped_packets_outgoing_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.DroppedPacketsOutgoingPersec)
        virtual_network_adapter_extensions_dropped_packets_incoming_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.ExtensionsDroppedPacketsIncomingPersec)
        virtual_network_adapter_extensions_dropped_packets_outgoing_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.ExtensionsDroppedPacketsOutgoingPersec)
        virtual_network_adapter_i_psecoffload_bytes_receive_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.IPsecOffloadBytesReceivePersec)
        virtual_network_adapter_i_psecoffload_bytes_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.IPsecoffloadBytesSentPersec)
        virtual_network_adapter_multicast_packets_received_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.MulticastPacketsReceivedPersec)
        virtual_network_adapter_multicast_packets_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.MulticastPacketsSentPersec)
        virtual_network_adapter_packets_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.PacketsPersec)
        virtual_network_adapter_packets_received_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.PacketsReceivedPersec)
        virtual_network_adapter_packets_sent_persec \
            .labels(adapter=virtual_network_adapter.Name) \
            .set(virtual_network_adapter.PacketsSentPersec)

    hyper_v_virtual_switch = GetObject('winmgmts:') \
        .InstancesOf('Win32_PerfFormattedData_NvspSwitchStats_HyperVVirtualSwitch')
    for virtual_switch in hyper_v_virtual_switch:
        virtual_switch_broadcast_packets_received_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.BroadcastPacketsReceivedPersec)
        virtual_switch_broadcast_packets_sent_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.BroadcastPacketsSentPersec)
        virtual_switch_bytes_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.BytesPersec)
        virtual_switch_bytes_received_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.BytesReceivedPersec)
        virtual_switch_bytes_sent_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.BytesSentPersec)
        virtual_switch_directed_packets_received_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.DirectedPacketsReceivedPersec)
        virtual_switch_directed_packets_sent_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.DirectedPacketsSentPersec)
        virtual_switch_dropped_packets_incoming_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.DroppedPacketsIncomingPersec)
        virtual_switch_dropped_packets_outgoing_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.DroppedPacketsOutgoingPersec)
        virtual_switch_extensions_dropped_packets_incoming_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.ExtensionsDroppedPacketsIncomingPersec)
        virtual_switch_extensions_dropped_packets_outgoing_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.ExtensionsDroppedPacketsOutgoingPersec)
        virtual_switch_learned_mac_addresses \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.LearnedMacAddresses)
        virtual_switch_learned_mac_addresses_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.LearnedMacAddressesPersec)
        virtual_switch_multicast_packets_received_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.MulticastPacketsReceivedPersec)
        virtual_switch_multicast_packets_sent_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.MulticastPacketsSentPersec)
        virtual_switch_numberof_send_channel_moves_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.NumberofSendChannelMovesPersec)
        virtual_switch_numberof_vmq_moves_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.NumberofVmqMovesPersec)
        virtual_switch_packets_flooded \
            .labels(vswitch=virtual_switch.Name) \
            .inc(float(virtual_switch.PacketsFlooded) - virtual_switch_packets_flooded.labels(
            vswitch=virtual_switch.Name)._value.get())
        virtual_switch_packets_flooded_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PacketsFloodedPersec)
        virtual_switch_packets_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PacketsPersec)
        virtual_switch_packets_received_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PacketsReceivedPersec)
        virtual_switch_packets_sent_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PacketsSentPersec)
        virtual_switch_purged_mac_addresses \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PurgedMacAddresses)
        virtual_switch_purged_mac_addresses_persec \
            .labels(vswitch=virtual_switch.Name) \
            .set(virtual_switch.PurgedMacAddressesPersec)


def main():
    start_wsgi_server(8000)
    while True:
        update_metrics()
        time.sleep(5)


if __name__ == '__main__':
    main()
